name: Release Drafter

on:
  push:
    branches:
      - main  # Dostosuj do swojej głównej gałęzi, np. "master" lub "develop"
  pull_request:
    types:
      - closed

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6.0.0
        with:
          config-name: release-drafter-config.yml
