name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release/**
  pull_request:
    branches:
      - release/**
    # Only following types are handled by the action, but one can default to all as well
    # types: [opened, reopened, synchronize]
    # Only following types are handled by the action, but one can default to all as well
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract branch name
        run: |
          # Wyciągnij pełną nazwę gałęzi z GITHUB_REF
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch name: $BRANCH_NAME"

          # Wyciągnij numer wersji z gałęzi w formacie release/XYZ
          if [[ "$BRANCH_NAME" =~ ^release/(.+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            echo "Branch name does not match expected format 'release/*'"
            exit 0
          fi

          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: generate release notes
        # Drafts your next Release notes as Pull Requests are merged into "master"
        uses: release-drafter/release-drafter@v6
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: release-drafter-config.yml
          version: ${{ steps.extract_version.outputs.version }}
          #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}