name: Release Drafter

on:
  push:
    branches:
      - 'release/**' # Wszystkie gałęzie zaczynające się od "release/"
  pull_request:
    branches:
      - master

jobs:
  draft-release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from branch name
        id: extract-version
        run: |
          # extract version from release branch name
          VERSION=${GITHUB_REF#refs/heads/release/}
          echo "Extracted version: $VERSION" # Zapis do logów
          echo "::set-output name=version::$VERSION"
        outputs:
          version: ${{ steps.extract-version.outputs.version }}

      - name: Log extracted version
        run: |
          echo "Running release drafter for version: ${{ steps.extract-version.outputs.version }}"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.extract-version.outputs.version }} # Przekaż wersję
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
