name: Release Drafter

on:
  push:
    branches:
      - main  # Zmień, jeśli używasz innej głównej gałęzi
  pull_request:
    types:
      - closed

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5.21.0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
